export type ReassuranceStatus = '안심' | '확인 필요' | '긴급'
export type PickupMode = 'hospital_front' | 'home_taxi_together' | 'partner_mobility' | 'family_dropoff'
export type TimelineStatus = 'done' | 'current' | 'waiting' | 'risk'
export type TimelineItem = { id: string; title: string; status: TimelineStatus; scheduledAt?: string; actualAt?: string; note?: string; actor?: string }
export type ManagerTrustCard = { id: string; name: string; photoUrl?: string; trustScore: number; completedCount: number; specialties: string[]; availableRegions: string[]; hasVehicle: boolean; directTransportAvailable: boolean; verifiedBadges: string[]; lastMatchedNote?: string }
export type CareReport = { id: string; appointmentId: string; summary: string; progress: string[]; medicalGuidance: string[]; testsAndMedication: string[]; nextAppointment: string[]; costs: string[]; condition: string; nextActions: string[]; managerNote?: string }
export type WorryCategory = 'hospital' | 'meal' | 'medication' | 'discharge' | 'documents' | 'recurring' | 'not_sure' | 'emergency'
export type IntakeChannel = 'phone' | 'kakao' | 'photo' | 'simple_form'
export type CarePack = { code: string; title: string; primaryWorry: WorryCategory; description: string; included: string[]; channels: IntakeChannel[]; socialCareReady?: boolean }
export type IntegrationConnector = { code: string; title: string; purpose: string; status: 'ready' | 'needs_key' | 'planned'; envKeys: string[] }
